name: Generate Languages Card

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Generate Languages SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Name of the file
          filename: github-languages.svg
          
          # 1. SAVE TO SEPARATE BRANCH
          committer_branch: output
          
          user: Gcinani-Leeon
          
          # 2. TURN OFF DEFAULT STATS (Removes the header, followers, etc.)
          base: ""
          
          # 3. TURN ON ONLY LANGUAGES
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
