name: Generate GitHub Metrics

on:
  # Run automatically every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allow you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    
    # We learned this trick last time! This gives the robot permission to save the image.
    permissions:
      contents: write 

    steps:
      - name: Generate Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          # This tells the action to use the default security token to read your stats
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Sets the file name it will save as
          filename: github-metrics.svg
          
          # Base settings
          user: Gcinani-Leeon
          template: classic
          base: header, repositories
          config_timezone: Africa/Johannesburg
          
          # Plugin: Languages (To get that compact progress bar)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          
          # Plugin: Isometric Calendar (The green 3D blocks!)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # This pushes the finished SVG to a branch called "output"
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: metrix
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
